name = "hidden-qr"
compatibility_date = "2025-04-13"
compatibility_flags = ["nodejs_compat"]
main = "./public/qr-worker.js"

[build]
command = ""

[site]
bucket = "./public"
include = ["**/*"]
exclude = ["node_modules"]

[vars]
MAX_IMAGE_SIZE = "2000"
QR_CELL_SIZE = "3"
EDGE_THRESHOLD = "50"

[env.production]
CF_PAGES_CACHE_BUST = "v4"  # 按需调整
