# 部署配置
name = "hidden-qr"
compatibility_date = "2024-03-20"
main = "./public/qr-worker.js"  # 主入口文件
node_compat = true              # 启用Node.js兼容模式

[build]
command = ""                    # 无需构建步骤
upload.format = "modules"       # 使用ESM模块格式

[site]
bucket = "./public"             # 静态资源目录
