# wrangler.toml
name = "hidden-qr"
compatibility_date = "2024-03-20"
main = "./public/qr-worker.js"  # 关键配置

[site]
bucket = "./public"             # 静态资源目录

[build]
command = "echo 'No build needed'"
