name = "hidden-qr"
compatibility_date = "2025-04-16"
compatibility_flags = ["nodejs_compat"]
main = "./public/qr-worker.js"

[build]
upload_format = "modules"
module_type = "esm"

[site]
bucket = "./public"
include = ["**/*"]
exclude = ["node_modules"]

[vars]
MAX_IMAGE_SIZE = "2000"
QR_CELL_SIZE = "3"
EDGE_THRESHOLD = "50"

[env.production]
CF_PAGES_CACHE_BUST = "v1"  # 按需调整

[[rules]]
globs = ["**/*.js"]  # 添加globs字段指定匹配规则
type = "ESModule"
